---
title: "Nobel winners"
author: "NOAH"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    toc_float: yes
---

```{r load-packages, message=FALSE}
library(tidyverse)
```

Let's first load the data:

```{r load_data, eval=TRUE}
nobel <- read.csv(file = "data-raw/nobel.csv")
```

Then let's split the data into two:

```{r split_data, eval=TRUE}
# stem laureates
nobel_stem <- nobel %>%
  filter(category %in% c("Physics", "Medicine", "Chemistry", "Economics"))

# non-steam laureates
nobel_nonstem <- nobel %>%
  filter(category %in% c("Peace", "Literature"))
```

And finally write out the data:
Write out the two data frames to nobel-stem.csv and nobel-nonstem.csv, respectively, to data/.

```{r writing_out}
# add code for writing out the two data frames here
dir.create("data")
write.csv(nobel_stem, "data/nobel-stem.csv")
write.csv(nobel_nonstem, "data/nobel-nonstem.csv")
```

## References {#references}
1. Assignment Adapted from [Mine Cetinkaya-Rundel's Data Science in a Box](https://github.com/rstudio-education/datascience-box)